### ISSUE TITLE
咨询下权重数据来源

### ISSUE THREAD

**Issue by plutotree** [limaofu/cof86#3]
首先感谢辛苦整理这么完整的库~，有两个问题想咨询下：
1. 这里的单字和词语的权重数据是来源于哪里的？
2. 扩展单字的拆分方法是手动整理的么？或者有规范的来源吗？

**Comment by limaofu** [comment]
> 首先感谢辛苦整理这么完整的库~，有两个问题想咨询下：
> 
> 1. 这里的单字和词语的权重数据是来源于哪里的？                             rime-wubi
> 2. 扩展单字的拆分方法是手动整理的么？或者有规范的来源吗？      manual
