### ISSUE TITLE
怎么用呢

### ISSUE THREAD

**Issue by zhaoqiang1024** [limaofu/cof86#4]
怎么用呢，里面有一些文件在鼠须管里有，是需要覆盖还是怎么着

**Comment by limaofu** [comment]
> 怎么用呢，里面有一些文件在鼠须管里有，是需要覆盖还是怎么着

overwrite

**Comment by limaofu** [comment]
closed

**Comment by limaofu** [comment]
按需使用，

zhaoqiang1024 ***@***.***> 于 2024年10月28日周一 19:13写道：
